# Generated by Django 3.2.4 on 2021-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill_course',
            fields=[
                ('course_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('course_category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
