# Generated by Django 3.2.4 on 2021-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
